# PriceSense configuration
data_csv: "C:\\Users\\sagni\\Downloads\\Price Sense\\archive\\flipkart_com-ecommerce_sample.csv"
artifact_dir: "C:\\Users\\sagni\\Downloads\\Price Sense"
database_url: "sqlite:///./pricesense.db"

# Demo/seed settings
seed_days: 60           # how many days of synthetic price history to seed
price_noise_frac: 0.08  # +- 8% daily noise
deal_drop_prob: 0.07    # probability of a "deal day" (extra drop)
deal_drop_frac: 0.12    # extra drop size on deal days
top_n_products: 300     # limit products during demo seeding (for speed)

# Training settings
lstm_sequence_len: 7
lstm_epochs: 5
lstm_batch_size: 64
test_split: 0.2

# Celery/Redis (optional). If you don't want Celery, ignore these.
redis_url: "redis://localhost:6379/0"
